name: Publish to Conda

on:
  workflow_dispatch:

jobs:
  publish_conda:
    name: Build and Upload to Conda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.11"
          channels: conda-forge,defaults

      - name: Install Conda Build Tools
        run: |
          conda install -y conda-build anaconda-client conda-verify
          conda config --add channels conda-forge

      - name: Build Conda Package
        run: conda build -c conda-forge recipe/

      - name: Get Package Path
        run: echo "PACKAGE_PATH=$(conda build --output recipe/)" >> $GITHUB_ENV

      - name: Upload to Anaconda Cloud
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate base
          which anaconda
          anaconda upload --user algotom $PACKAGE_PATH
